// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aztnzmymohftmutxjfqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dG56bXltb2hmdG11dHhqZnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjcxNzEsImV4cCI6MjA2MTQ0MzE3MX0.7g9UFsItEk3R7Nyv8y8OwycvXvQCIhJFLUq0csvJmPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);