
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oregxnkiwqaojyxervir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZWd4bmtpd3Fhb2p5eGVydmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDU3OTUsImV4cCI6MjA1OTc4MTc5NX0.Ty9BITPVGOrGK4VFnzZ2ZF6xxZE9VHxkfB_mV27rs4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
